In [7]:
# 사칙연산을 하는 클래스 정의 : 클래스 이름, 변수, 함수
# 변수는 두개, 함수(메서드) 4개

class FourCal:
    
    # 초기화 메서드
    def __init__(self, first, second):
        # 클래스의 인스턴스 변수
        self.first = first
        self.second = second 
    
    # 클래스에서 함수를 정의할 때에는 반드시 self 매개변수를 받아야 한다
    # self는 인스턴스 자신을 의미한다
    # => 객체 지시를 가르키는 변수 (객체의 주소)
    def setdata(self, first, second):
        self.first = first
        self.second = second

In [2]:
cal_1 = FourCal()

In [3]:
cal_1.setdata(4, 2)

In [4]:
print(cal_1.first)  # 4
print(cal_1.second)  # 2

4
2


In [5]:
cal_2 = FourCal()

In [6]:
cal_2.first

AttributeError: 'FourCal' object has no attribute 'first'

In [8]:
# 학생 class 생성 -> 객체 생성
# 변수: 학번, 이름, 국어점수, 영어점수, 수학점수
# 기능: 전체 데이터 출력하는 메서드 (이름, 학번, 총점, 평균ㄴㄴ)
#   총점 계산
#   평균 계산

class Student:
    def __init__(self, student_id, name, korean_score, english_score, math_score):
        self.student_id = student_id
        self.name = name
        self.korean_score = korean_score
        self.english_score = english_score
        self.math_score = math_score

    def total_score(self):
        return self.korean_score + self.english_score + self.math_score

    def average_score(self):
        return self.total_score() / 3

    def display_info(self):
        print(f"학번: {self.student_id}, 이름: {self.name}, 총점: {self.total_score()}, 평균: {self.average_score():.2f}")


In [9]:
student = Student(2023001, "홍길동", 85, 90, 95)
student.display_info()  # 학번: 2023001, 이름: 홍길동, 총점: 270, 평균: 90.00

학번: 2023001, 이름: 홍길동, 총점: 270, 평균: 90.00


- 표준모듈 간단한 사용


In [1]:
import datetime

In [12]:
day1 = datetime.date(2025 , 6, 12)

In [8]:
print(day1)

2025-06-12


In [13]:
day2 = datetime.date(2025 , 1, 11)

In [15]:
print(day1-day2)  # 152 days

152 days, 0:00:00


In [16]:
import time

In [ ]:
time.time()  # 현재 시간을 초 단위로 반환

1749711417.249818

In [ ]:
time.localtime()  # 현재 시간을 struct_time 객체로 반환.

time.localtime().tm_mon  # 현재 월      

6

In [ ]:
time.ctime() # 현재 시간을 문자열로 반환

'Thu Jun 12 15:59:19 2025'

In [ ]:
import random

random.randint(1, 10)  # 1부터 10 사이의 정수 중 랜덤으로 하나 반환
random.choice(['apple', 'banana', 'cherry'])  # 리스트에서 랜덤으로 하나 선택

'apple'

In [34]:
random.random()  # 0.0 이상 1.0 미만의 랜덤 실수 반환

0.45887241273506263

In [101]:
random.randbytes(3)  # 5바이트 길이의 랜덤 바이트 문자열 반환

b'\xcc\x8c\xdd'

In [103]:
random.choice(['apple', 'banana', 'cherry'])  # 리스트에서 랜덤으로 하나 선택

'apple'

In [120]:
type(random.sample(['apple', 'banana', 'cherry'], 2))  # 리스트에서 랜덤으로 2개 선택

list

In [ ]:
import os

In [127]:
os.getcwd()  # 현재 프로세스의 ID 반환

'c:\\project\\py_project'

In [128]:
import json

In [ ]:
with open('data.json', 'r', encoding='utf-8') as f:
    data = json.load(f)  # JSON 파일 읽기
    print(data)

{'name': 'Ditto', 'age': 2, 'species': 'Transform '}


In [ ]:
json_str_data = json.dumps(data, ensure_ascii=False)  # JSON 문자열로 변환
print(type(json_str_data))  # <class 'str'>
# json은 규격이 있는 문자열일 뿐이다.


<class 'str'>


- 외부라이브러리

In [139]:
import numpy as np

In [140]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
print(arr, type(arr))  # [1 2 3 4 5 6]

[1 2 3 4 5 6] <class 'numpy.ndarray'>


In [143]:
# 배열의 생성
# 0으로 채워지는 배열 생성
ze = np.zeros((2, 3))  # 2행 3열의 배열 생성
print(ze, type(ze))  # [[0. 0. 0.] [0. 0. 0.]]

[[0. 0. 0.]
 [0. 0. 0.]] <class 'numpy.ndarray'>


In [144]:
# 일련번호 생성되는 배열
# 0~10 사이의 숫자를 2씩 간격
seq_1 = np.arange(0,10,2)
print(seq_1, type(seq_1))  # [0 2 4 6 8]

[0 2 4 6 8] <class 'numpy.ndarray'>


In [147]:
# 지정된 범위 안에서 동일한 간격으로 숫자를 생성
# 0~1 5개로 구분
lispace = np.linspace(1, 10, 4)
print(lispace, type(lispace))  # [ 0.   2.75  5.5   8.25 11.  ]

[ 1.  4.  7. 10.] <class 'numpy.ndarray'>


In [148]:
# 배열의 속성 확인
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1.shape)  # (2, 3) - 2행 3열

(2, 3)


In [ ]:
print(type(arr1))  # <class 'numpy.ndarray'> - numpy 배열 객체z

<class 'numpy.ndarray'>


In [150]:
print(arr1.ndim)  # 2 - 배열의 차원 수

2
